name: Build Documentation

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  documentation:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        run: |
          sudo apt install ffmpeg pngquant imagemagick
          wget https://github.com/vgmstream/vgmstream-releases/releases/download/nightly/vgmstream-linux-cli.tar.gz
          tar -zxf vgmstream-linux-cli.tar.gz
          mkdir bin
          mv vgmstream-cli bin
          wget https://imagemagick.org/archive/binaries/magick
          mv magick bin
          chmod a+x bin/*
          echo "${PWD}/bin" >> $GITHUB_PATH
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
      - name: Setup Python Environment
        run: |
          cd unpack
          pdm install
          source .venv/bin/activate
          pip install -r downloader/requirements.txt
      - name: Download Resources
        run: |
          cd unpack
          source .venv/bin/activate
          cd downloader
          python downloader.py
      - name: Unpack resources
        run: |
          cd unpack
          source .venv/bin/activate
          python -m gfunpack downloader/output -o .
          rm audio/*/*.wav audio/*/*.acb
          cp audio/audio.json images/backgrounds.json images/characters.json ../src/assets
          mv audio ../public
          mv images ../public
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.5.0
          run_install: false
      - name: Setup PNPM Workspace
        run: |
          pnpm install
      - name: Build Site
        run: |
          pnpm build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME  }}
          directory: dist
