name: Build Documentation

on:
  workflow_dispatch:
  push:

jobs:
  documentation:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          lfs: true

      - name: Install Windows Dependencies
        run: |
          choco install ffmpeg pngquant imagemagick git-lfs nodejs -y --no-progress
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1" -Force
          Update-SessionEnvironment
          ffmpeg -version
          pngquant --version
          magick -version
          git lfs version
          node --version

      - name: Install PowerShell Core
        run: |
          choco install powershell-core -y --no-progress
          $pwshPath = "C:\Program Files\PowerShell\7"
          echo "Adding PowerShell Core to PATH: $pwshPath"
          echo "$pwshPath" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8
          $env:Path = "$pwshPath;$env:Path"
          pwsh --version

      - name: Install vgmstream
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://github.com/vgmstream/vgmstream-releases/releases/download/nightly/vgmstream-win64.zip" -OutFile "vgmstream.zip"
          New-Item -ItemType Directory -Path "bin" -Force | Out-Null
          Expand-Archive -Path "vgmstream.zip" -DestinationPath "bin" -Force
          Remove-Item -Path "vgmstream.zip" -Force
          
          echo "### Contents of bin folder:"
          Get-ChildItem -Path "bin" | Format-Table FullName
          
          # Правильная проверка версии vgmstream
          Write-Host "VGMStream version:"
          & "bin\vgmstream-cli.exe" -V
          
          $binPath = "$pwd\bin"
          echo "Adding bin to PATH: $binPath"
          echo "$binPath" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8
          $env:Path = "$binPath;$env:Path"
          
          Write-Host "VGMStream version via PATH:"
          vgmstream-cli.exe -V

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install PDM
        run: |
          python -m pip install pdm
          $pdmPath = "$env:APPDATA\Python\Python311\Scripts"
          echo "Adding PDM to PATH: $pdmPath"
          echo "$pdmPath" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8
          $env:Path = "$pdmPath;$env:Path"
          pdm --version

      - name: Setup PNPM
        run: |
          npm install -g pnpm
          $pnpmPath = "$env:APPDATA\npm"
          echo "Adding PNPM to PATH: $pnpmPath"
          echo "$pnpmPath" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8
          $env:Path = "$pnpmPath;$env:Path"
          pnpm -v

      - name: Verify Tools
        run: |
          Get-Command python, node, pdm, pnpm, ffmpeg, pngquant, magick, git, vgmstream-cli | Format-Table Name, Source
          $env:Path -split ';' | Where-Object { $_ } | Sort-Object | Out-Host
          python -V
          node -v

      - name: Restore Cached Resources
        id: restore-gf-downloader-resources
        uses: actions/cache/restore@v4
        with:
          path: |
            unpack/downloader/output
          key: gf-downloader-resources-${{ runner.os }}

      - name: Setup Python Environment
        run: |
          cd unpack
          pdm use python
          pdm install --no-lock
          .\.venv\Scripts\activate
          pip install -r downloader/requirements.txt

      - name: Download Resources
        run: |
          cd unpack
          .\.venv\Scripts\activate
          New-Item -ItemType Directory -Path "downloader/resdata" -Force
          Copy-Item -Path "gf-data-rus/resdata_no_hash.json" -Destination "downloader/resdata/us_resdata.json"
          cd downloader
          (Get-Content config.json5) -replace '"ch"', '"us"' | Set-Content config.json5
          git apply ../downloader.patch
          Compress-Archive -Path "resdata/us_resdata.json" -DestinationPath "resdata.zip"
          python downloader.py --downloadres 0 --abname

      - name: Cache Downloaded Resources
        uses: actions/cache/save@v4
        with:
          path: |
            unpack/downloader/output
          key: ${{ steps.restore-gf-downloader-resources.outputs.cache-primary-key }}

      - name: Restore Cached Resources (images)
        id: restore-image-resources
        uses: actions/cache/restore@v4
        with:
          path: |
            unpack/images
          key: gf-image-resources-${{ runner.os }}

      - name: Unpack images
        run: |
          cd unpack
          Copy-Item -Path "fixed-data\*" -Destination "gf-data-rus" -Recurse
          .\.venv\Scripts\activate
          python tests/test_backgrounds.py
          python tests/test_characters.py

      - name: Cache Resources (images)
        uses: actions/cache/save@v4
        with:
          path: |
            unpack/images
          key: ${{ steps.restore-image-resources.outputs.cache-primary-key }}

      - name: Restore Cached Resources (audio)
        id: restore-audio-resources
        uses: actions/cache/restore@v4
        with:
          path: |
            unpack/audio
          key: gf-audio-resources-${{ runner.os }}

      - name: Unpack audio
        run: |
          cd unpack
          .\.venv\Scripts\activate
          python tests/test_audio.py

      - name: Cache Resources (audio)
        uses: actions/cache/save@v4
        with:
          path: |
            unpack/audio
          key: ${{ steps.restore-audio-resources.outputs.cache-primary-key }}

      - name: Unpack resources
        run: |
          cd unpack
          .\.venv\Scripts\activate
          python -m gfunpack downloader/output -o .

      - name: Move Resources
        run: |
          cd unpack
          $assets = @(
              "audio/audio.json",
              "images/backgrounds.json",
              "images/characters.json",
              "stories/stories.json",
              "stories/chapters.json"
          )
          Copy-Item -Path $assets -Destination "../src/assets" -Force
          Move-Item -Path "audio", "images", "stories" -Destination "../public" -Force

      - name: Install Node dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm list --depth 0

      - name: Build Site
        run: |
          pnpm build-index
          pnpm build
          
          # Проверка результата сборки
          if (Test-Path -Path dist) {
              echo "dist folder created successfully"
              Get-ChildItem -Recurse dist | Format-Table FullName
          } else {
              Write-Error "dist folder not found!"
              Get-ChildItem -Recurse | Format-Table FullName
              exit 1
          }

      - name: Upload dist as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist-debug
          path: dist
          retention-days: 1

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: dist
        timeout-minutes: 10