- name: Install Dependencies
  run: |
    # Явный импорт профиля перед установкой
    Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1" -Force
    
    # Установка с проверкой
    choco install -y ffmpeg imagemagick pngquant --force
    Update-SessionEnvironment
    
    # Проверка установки
    ffmpeg -version
    magick -version
    pngquant --version
    
    # Скачивание vgmstream
    $ProgressPreference = 'SilentlyContinue'
    Invoke-WebRequest -Uri "https://github.com/vgmstream/vgmstream-releases/releases/download/nightly/vgmstream-win64.zip" -OutFile "vgmstream-win64.zip"
    Expand-Archive -Path "vgmstream-win64.zip" -DestinationPath "vgmstream"
    
    # Проверка содержимого архива
    echo "### Contents of vgmstream folder:"
    Get-ChildItem -Recurse vgmstream | Format-Table FullName
    
    # Поиск исполняемого файла (структура может меняться)
    $vgmstreamExe = Get-ChildItem -Path vgmstream -Recurse -Include "test.exe", "vgmstream-cli.exe" | Select-Object -First 1
    
    if (-not $vgmstreamExe) {
        Write-Error "VGMStream executable not found!"
        exit 1
    }
    
    New-Item -ItemType Directory -Path "bin" -Force | Out-Null
    Copy-Item -Path $vgmstreamExe.FullName -Destination "bin\vgmstream-cli.exe" -Force
    
    # Поиск magick.exe
    $magickPath = Get-Command magick | Select-Object -ExpandProperty Source -ErrorAction SilentlyContinue
    if (-not $magickPath) {
        $magickPath = Get-ChildItem -Path "C:\Program Files\ImageMagick-*" -Recurse -Filter "magick.exe" | Select-Object -First 1
    }
    
    if ($magickPath) {
        Copy-Item -Path $magickPath -Destination "bin\" -Force
    } else {
        Write-Error "magick.exe not found!"
    }
    
    # Добавление в PATH
    $newPath = "$pwd\bin"
    $env:Path = "$newPath;$env:Path"
    echo "::add-path::$newPath"
    
    # Проверка доступности бинарников
    vgmstream-cli.exe -v
    bin\magick.exe -version